/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Photo = IDL.Record({
  'height' : IDL.Nat,
  'mimeType' : IDL.Text,
  'bytes' : IDL.Vec(IDL.Nat8),
  'width' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DiaryEntry = IDL.Record({
  'text' : IDL.Text,
  'colorTag' : IDL.Text,
  'timestamp' : IDL.Int,
  'photo' : IDL.Opt(Photo),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addEntry' : IDL.Func([IDL.Text, IDL.Int, IDL.Text], [], []),
  'addEntryWithPhoto' : IDL.Func([IDL.Text, IDL.Int, Photo, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteDiaryEntry' : IDL.Func([IDL.Int], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEntries' : IDL.Func([], [IDL.Vec(DiaryEntry)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Photo = IDL.Record({
    'height' : IDL.Nat,
    'mimeType' : IDL.Text,
    'bytes' : IDL.Vec(IDL.Nat8),
    'width' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DiaryEntry = IDL.Record({
    'text' : IDL.Text,
    'colorTag' : IDL.Text,
    'timestamp' : IDL.Int,
    'photo' : IDL.Opt(Photo),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addEntry' : IDL.Func([IDL.Text, IDL.Int, IDL.Text], [], []),
    'addEntryWithPhoto' : IDL.Func(
        [IDL.Text, IDL.Int, Photo, IDL.Text],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteDiaryEntry' : IDL.Func([IDL.Int], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEntries' : IDL.Func([], [IDL.Vec(DiaryEntry)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };